name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job_npm_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install npm
        run: npm install
  job_npm_test:
    needs: job_npm_install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: npm test
        run: npm test
    
