name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Reduce SHA
        id: reduce-sha
        run: echo "VAR_SHA_REDUCE=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Create issue
        shell: bash
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.TOKEN_EX3 }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ steps.reduce-sha.outputs.VAR_SHA_REDUCE }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
            }' \
          --fail
