name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Reduce SHA
        id: reduce-sha
        run: echo "VAR_SHA_REDUCE=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Create issue
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN_EX3 }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/issues \
          -d '{"title":"SHA-7: ${{ env.reduce-sha.outputs.VAR_SHA_REDUCE }}","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'
